namespace:
  prefix: alt
  uri: ALT.Policies.1.0
policies:
- altVersion: P10
  category: ALT_Security
  class: Machine
  description: Описание политики
  displayName: Простая политика
  key: Software\BaseALT\Policies\Control
  name: TestPPPPP
  type: simple
  valueName: TestPPPPP
  valueType: string
